### ISSUE TITLE
Swap the role of G1 and G2.

### ISSUE THREAD

**Issue by herumi** [herumi/bls#21]
https://github.com/herumi/bls/issues/19#issuecomment-442533827
By @rauljordan
>we want to have signatures in G2 and public keys in G1. How difficult would this be to change based on your implementation?

**Comment by herumi** [comment]
The current mcl supports only precomputing Miller loop for a fixed Q in G2.
It is a hard task to make the function for a fixed P in G1.
But it is not so hard to support to swap G1 and G2 unless using the optimized Miller loop.

**Comment by herumi** [comment]
Hi @rauljordan, the latest version of `bls` supports `make BLS_SWAP_G=1`, which swaps the role of G1 and G2.

Feature works
* `verify` is slower than that of non-swap version because mcl does not support precomputing miller loop for G1, which is a hard task.
* ffi/go/bls.go does not support this feature yet because I do not know how to write good code for bls.go to swap G1 and G2.

**Comment by mortdeus** [comment]
@herumi

"It is a hard task to make the function for a fixed P in G1."


Can you clarify what you mean by " hard task" in this sentence? 

Do you mean "hard"  as in computationally difficult to generate the precompiled miller loop that takes P instead of Q? 

Or do you mean hard as in a lot of extra work to implement this feature? 

Im trying to understand why BLS_SWAP_G=1 works in general except for precomputed miller loop?

**Comment by herumi** [comment]
It is not computationally difficult.

>Or do you mean hard as in a lot of extra work to implement this feature?

Yes.

**Comment by herumi** [comment]
>ffi/go/bls.go does not support this feature yet because I do not know how to write >good code for bls.go to swap G1 and G2.

I refactored ffi/go/bls.go and cgo supports to swap G1 and G2 though it took a long time.

```
make clean
make BLS_SWAP_G=1
make test_go384_256_swapg
```
runs well  now.
