### ISSUE TITLE
Question about rogue blskey attack?

### ISSUE THREAD

**Issue by LeoHChen** [herumi/bls#44]
Hi,

Just wondering if this implementation of BLS multisig fixed the "bls rogue public key attack" mentioned in this paper. https://crypto.stanford.edu/~dabo/pubs/papers/BLSmultisig.html

**Comment by herumi** [comment]
Thank you for your advice. I know the paper and want to implement it.
But the standard hash functions in that scheme have not yet standardized as far as I know. Is it okay to decide the hash function appropriately?

**Comment by coolcottontail** [comment]
We can just leave hash function as a parameter.  Actually the hash function doesn't matter that much, a sha256 of the raw bytes should be enough for this purpose.

In order to implement the new BLS,  we need a function to do scalar multiplication of points in G0 (signature) and G1 (pubkey). 

Below is the algorithm described in Golang.  I need two functions:

func scalarMulitpleinG0(s Scalar,  P G0) G0;
func scalarMulitpleinG0(s Scalar,  P G1) G1;


func AggregatePubKey(H1, pubKeys[]) { 
 AggregatedPubKey = new PubKey;
 for(i in range len(pubKeys)) {
   hashScalar = H1(pubKeys[i]))
   AggregatedPubKey.add( ScalarMulitpleInG0(hashScalar, pubKey[i])))); 

 return AggregatedPubKey;
}

func AggregateSignature(H1, pubKeys[], sigs[]) { 
 AggregatedSig = new Signature ;
 for(i in range len(pubKeys)) {
   hashScalar = H1(pubKeys[i]))
   AggregatedSig.add( ScalarMulitpleInG1(hashScalar, sigs[i])))); 

return AggregatedSig;
}

**Comment by herumi** [comment]
@coolcottontail 
Thank you for your propose.
H1() depends on all pk_1, ..., pk_n and so each t_i depends on all pk_1, ..., pk_n.
so for example, I think that it is better that h:=sha256(pk1, ..., pkn), ti:=sha256(h, i).

And mclBnG1_mulVec, mclBnG2_mulVec can get a little faster than sum_i agg += sigma[i] * t[i].

There are on thing to consider. bls/mcl avoids dynamic memory allocation because of WebAssembly, So the code will be a little complex.

**Comment by herumi** [comment]
I'm sorry for the too-late response.
I've implemented it at [dev](https://github.com/herumi/bls/commit/df076802b44421eaf70bb97290f33cce4cecaee4).
The hash function is what I selected temporally. So it may be modified int the future.
